### PR TITLE
Summon Fixes #665 #928 #971

### LINKED ISSUE #665: Monster summon not working properly
When a player is around, monsters from the same floor and some below/above start to move. The problem is: they start to summon too. So imagine places like the Alchemist Quarter or Drefia, when many creatures are capable to summon, this can get very annoying.

The monster should only summon when a player is targeted -in the same way attacks are triggered-, it works that way in Tibia, tested right now.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1446529-monster-summon-not-working-properly?utm_campaign=plugin&utm_content=tracker%2F392151&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F392151&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by PrinterLUA**
Should close these issues:
https://github.com/otland/forgottenserver/issues/665
https://github.com/otland/forgottenserver/issues/928
https://github.com/otland/forgottenserver/issues/971

### CODE REVIEW

File: src/monster.cpp [hunk 1]
```diff
@@ -932,7 +926,7 @@ void Monster::onThinkDefense(uint32_t interval)
 		}
 	}
 
-	if (!isSummon() && summons.size() < mType->maxSummons) {
+	if (!isSummon() && summons.size() < mType->maxSummons && hasFollowPath) {
```
Comment (EvulMastah) [inline src/monster.cpp]: Wouldnt it be better to check`attackedCreature` instead?

Comment (PrinterLUA) [inline src/monster.cpp]: Maybe, i thougt hasFollowPath check if the creature is reachable. But it does not. I have no idéa how it should behave, either summon when it has a target or summon if target is reachable.

Comment (PrinterLUA) [inline src/monster.cpp]: @marksamman 
I would love some feedback, so i can make the necessary changes, if there is needed.

Comment (marksamman) [inline src/monster.cpp]: There isn't much to comment code-wise. I'm mostly concerned about the side effects of these changes. Have they been thoroughly tested? Otherwise I rather keep this PR open until after the 1.2 release.

Comment (PrinterLUA) [inline src/monster.cpp]: I have not tested them throughly to be honest. But i have tested and everything run smooth.

Any tests you want me to do, since i tried the changes and they behaved like they were coded todo.

Comment (marksamman) [inline src/monster.cpp]: I'm not concerned that they're not working as intended, I'm concerned for unintended side effects that some of the changes may have. Since I don't know how long it'll take before we can release 1.2, I'll just merge this and worst case revert it if we solve the release blocking 1.2 issues (onStepIn/Out call stack overflows and crashes) and this turns out to cause issues that nobody wants to try to solve.

**Comment by marksamman** [comment]
Thanks!

File: src/monster.cpp (hunk 1 above)
Comment (vankk) [inline src/monster.cpp]: @marksamman Could you help us what do you want test? Also, I can test it.
I want see if there is any side effects of theses changes.

Comment (PrinterLUA) [inline src/monster.cpp]: Can you link me to the issues, so we can speed up the release of 1.2. I would love to take a look at it.

Comment (marksamman) [inline src/monster.cpp]: #1621, #1660

It's mostly the first one that's blocking the release.

Comment (PrinterLUA) [inline src/monster.cpp]: Ok Cheers, i will take a look on those and try reproduce.
