### PR TITLE
Fix monsters melee conditions.

### LINKED ISSUE #1372: Poisonous enemies poisoning at first hit
Like the title says, i tested with snakes and poison spiders and they poison at the first hit, even if they fail.
screenshot_1
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/16607478-poisonous-enemies-poisoning-at-first-hit?utm_campaign=plugin&utm_content=tracker%2F392151&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F392151&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mkalo**
Only apply melee conditions on successful hit.

This fixes #1372.

### CODE REVIEW

**Comment by ranisalt** [comment]
Ty m8

File: src/combat.cpp [hunk 1]
```diff
@@ -520,8 +520,12 @@ void Combat::CombatManaFunc(Creature* caster, Creature* target, const CombatPara
 	}
 }
 
-void Combat::CombatConditionFunc(Creature* caster, Creature* target, const CombatParams& params, CombatDamage*)
+void Combat::CombatConditionFunc(Creature* caster, Creature* target, const CombatParams& params, CombatDamage* data)
 {
+	if (params.origin == ORIGIN_MELEE && data && data->primary.value == 0 && data->secondary.value == 0) {
```
Comment (raymondtfr) [inline src/combat.cpp]: Shouldn't this first check if the *attacker* was a monster? otherwise, this may have unintended side-effects?

Comment (Mkalo) [inline src/combat.cpp]: I don't see why this would have side-effects, I don't think we have weapons that apply conditions for players.

**Comment by peonso** [comment]
A hit that deals no damage can poison. If the damage is blocked by shield there is no poison, but it can still poison if the residual damage not blocked by shield is blocked by armor and there is no damage.
