### PR TITLE
allocator traits are complaining about OutputMessageAllocator, fixes #2677

### LINKED ISSUE #2677: MSVS 2019 trips on outputmessage.cpp(82)
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. use MSVS 2019
2. use vcpkg
3. Build master branch

### Expected behaviour
Clean compilation

### Actual behaviour
Compilation error:
```
1>------ Build started: Project: theforgottenserver, Configuration: Debug x64 ------
1>outputmessage.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664: 'void std::_Normal_allocator_traits<_Alloc>::destroy<_Ty>(_Alloc &,_Ty *)': cannot convert argument 1 from '_Alloc' to '_Alloc &'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:         with
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:         [
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:             _Alloc=LockfreePoolingAllocator<OutputMessage,2048>,
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:             _Ty=OutputMessage
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:         ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:         and
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:         [
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:             _Alloc=OutputMessageAllocator
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:         ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:         and
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:         [
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:             _Alloc=LockfreePoolingAllocator<OutputMessage,2048>
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1580,1): error C2664:         ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory(646,17): message : see declaration of 'std::_Normal_allocator_traits<_Alloc>::destroy'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory(646,17): message :         with
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory(646,17): message :         [
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory(646,17): message :             _Alloc=LockfreePoolingAllocator<OutputMessage,2048>
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xmemory(646,17): message :         ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1578): message : while compiling class template member function 'void std::_Ref_count_obj_alloc2<OutputMessage,_Alloc>::_Destroy(void) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1578): message :         with
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1578): message :         [
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1578): message :             _Alloc=OutputMessageAllocator
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1578): message :         ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1609): message : see reference to class template instantiation 'std::_Ref_count_obj_alloc2<OutputMessage,_Alloc>' being compiled
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1609): message :         with
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1609): message :         [
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1609): message :             _Alloc=OutputMessageAllocator
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1609): message :         ]
1>C:\Users\User\code\forgottenserver\src\outputmessage.cpp(82): message : see reference to function template instantiation 'std::shared_ptr<OutputMessage> std::allocate_shared<OutputMessage,OutputMessageAllocator,>(const _Alloc &)' being compiled
1>C:\Users\User\code\forgottenserver\src\outputmessage.cpp(82): message :         with
1>C:\Users\User\code\forgottenserver\src\outputmessage.cpp(82): message :         [
1>C:\Users\User\code\forgottenserver\src\outputmessage.cpp(82): message :             _Alloc=OutputMessageAllocator
1>C:\Users\User\code\forgottenserver\src\outputmessage.cpp(82): message :         ]
1>Done building project "theforgottenserver.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

### Environment
Windows 10 / MSVS 2019

### PR DESCRIPTION
**Pull request by slavidodo**
Fixes #2677 
Edits suggested by @djarek

### CODE REVIEW

File: src/lockfree.h [hunk 1]
```diff
@@ -26,37 +26,46 @@
...
+struct LockfreeFreeList
+{
+	using FreeList = boost::lockfree::stack<void*, boost::lockfree::capacity<CAPACITY>>;
+	static FreeList& get()
+	{
+		static FreeList freeList;
+		return freeList;
+	}
+};
+
```
Comment (ranisalt) [inline src/lockfree.h]: Why not using a static variable instead of wrapping with a class?

Comment (slavidodo) [reply src/lockfree.h]: this is C++11 and variable templates were supported in C++14

**Comment by DSpeichert** [comment]
Approved on behalf of @djarek
