### PR TITLE
Fast monsters and players death

### LINKED ISSUE #3023: delayed monster body drop bug (fix inside)
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

Possibly a duplicate, but I can't find the original issue.

### Steps to reproduce (include any configuration/script required to reproduce)
1. spawn monsters
2. kill monsters

### Expected behaviour
body drops instantly (just like in official servers)

### Actual behaviour
body drops after a short delay dictated by EVENT_CREATURE_THINK_INTERVAL

### Reproduction rate
high, but unknown (depends on sync with interval)

### Reproduction environment
master branch, any os/hardware

### Potential solution
moving creatures death from here:
https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L3690

to here:
https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L4251

I don't have time to fix it myself and test stability in cases like when some admin decides to spam ue on his server and I don't know how to detect potential data races so I'm reporting it here with potential solution. In fact current implementation is better for big servers so you can make it toggleable in config.lua.

### PR DESCRIPTION
**Pull request by kygov**
Monsters and players will die immediately like on real tibia servers.

Fixes #3023

### CODE REVIEW

**Comment by MillhioreBT** [comment]
This is interesting and I really like it, the question now is: can this cause side effects? in my opinion it should not cause any problems

**Comment by robpot95** [comment]
Why not just put check Inside onDrainHealth, since you Only die by losing health. Then execute onDeath directly.

I dont Think it's a Good idea to send it through the dispatcher. This Will execute every time a creature die

**Comment by kygov** [comment]
@robpot95 I'm not sure about drainHealth since changeHealth is called in more places, for example here: https://github.com/otland/forgottenserver/blob/08231f423984f7db78b498f0ffdd7257ea6b1a95/src/monster.cpp#L1103

so drainHealth may miss some situations and monsters will not die.

About sending it through dispatcher, its main game thread and all actions perform there, I'm using it in this way on my servers and never had problems with crashes, memory leaks or something and I'm not sure about calling it without dispatcher.

File: src/creature.cpp [hunk 1]
```diff
@@ -759,6 +759,10 @@ void Creature::changeHealth(int32_t healthChange, bool sendHealthChange/* = true
 		health = std::max<int32_t>(0, health + healthChange);
 	}
 
+	if (health < 1) {
```
Comment (Lyuzera) [inline src/creature.cpp:762]: you can check `<= 0`

File: src/creature.cpp [hunk 2]
```diff
@@ -759,6 +759,10 @@ void Creature::changeHealth(int32_t healthChange, bool sendHealthChange/* = true
...
+		g_dispatcher.addTask(createTask(std::bind(&Game::executeDeath, &g_game, getID())));
+	}
+
 	if (sendHealthChange && oldHealth != health) {
```
Comment (Lyuzera) [inline src/creature.cpp:766]: I think this could be safer if it was above `executeDeath`, because `addCreatureHealth` uses `this` as argument.

File: src/game.cpp [hunk 3]
```diff
@@ -609,6 +609,14 @@ bool Game::removeCreature(Creature* creature, bool isLogout/* = true*/)
 	return true;
 }
 
+void Game::executeDeath(uint32_t creatureId)
+{
+	Creature* creature = getCreatureByID(creatureId);
+	if (creature && !creature->isRemoved() && creature->getHealth() < 1) {
```
Comment (Lyuzera) [inline src/game.cpp:615]: checking life again? I think it is not necessary.

File: src/creature.cpp (hunk 2 above)
Comment (kygov) [reply src/creature.cpp:762]: changed

File: src/game.cpp (hunk 3 above)
Comment (kygov) [reply src/game.cpp]: changed

File: src/game.cpp [hunk 4]
```diff
@@ -609,6 +609,14 @@ bool Game::removeCreature(Creature* creature, bool isLogout/* = true*/)
 	return true;
 }
 
+void Game::executeDeath(uint32_t creatureId)
+{
+	Creature* creature = getCreatureByID(creatureId);
+	if (creature && !creature->isRemoved()) {
```
Comment (nekiro) [inline src/game.cpp:615]: What if creature is removed, but not actually dead? I think better idea would be to check if health <= 0

File: src/creature.cpp [hunk 5]
```diff
@@ -762,6 +762,10 @@ void Creature::changeHealth(int32_t healthChange, bool sendHealthChange/* = true
...
 		g_game.addCreatureHealth(this);
 	}
+
+	if (health <= 0) {
+		g_dispatcher.addTask(createTask(std::bind(&Game::executeDeath, &g_game, getID())));
```
Comment (nekiro) [inline src/creature.cpp:767]: This method (changeHealth) is always executed in dispatchee thread anyway, so I guess you can just call that method directly?

**Comment by nekiro** [comment]
changeHealth is most likely executed in combatChangeHealth right? If so after you kill that monster there is still code that operates on that pointer in combat.cpp. Only reason it does not crash instantly is, because tfs stores deleted monsters for some time to free them later. 
https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L601
I would suggest moving that health check to here:
https://github.com/otland/forgottenserver/blob/master/src/combat.cpp#L796

**Comment by Znote** [comment]
I'm a bit worried about how this will play along with creatureconditions. 
#2554

**Comment by jo3bingham** [comment]
> I'm a bit worried about how this will play along with creatureconditions.
> #2554
> @jo3bingham

I don't see how it would cause any issues.

**Review by omarcopires — APPROVED** [review]

**Review by marmichalski — APPROVED** [review]
