### PR TITLE
Remove condition by Condition parameters (fixes #3544)

### LINKED ISSUE #3544: creature:removeCondition doesn't work properly with userdata
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Add the following test code at `data/scripts/talkactions/condition.lua`
```lua
local condition = Condition(CONDITION_HASTE)
condition:setParameter(CONDITION_PARAM_TICKS, 10000)
condition:setFormula(0.3, -12, 0.3, -12)

local talk = TalkAction("/test")
function talk.onSay(player, words, param)
	if player:hasCondition(CONDITION_HASTE) then
		print("remove")
		player:removeCondition(condition)
	else
		print("add")
		player:addCondition(condition)
	end
	return false
end

talk:register()
```

2. Run the `/test` command twice in game within 10 seconds, the condition should be added on the first execution and then removed on the second

### Expected behaviour
The haste condition should be added and removed respectively

### Actual behaviour
The haste condition is only added, but removing fails, even though `remove` is being printed in the console

### Related commits
https://github.com/otland/forgottenserver/commit/923f448f402392ee0c27632326da901947a724a8
https://github.com/otland/forgottenserver/commit/5d946f178e3f9e1ba48ba96e47ca7291bc4b6a4c

### Problematic code
It fails to find the condition with `std::find` in `Creature::removeCondition`
```cpp
void Creature::removeCondition(Condition* condition, bool force/* = false*/)
{
	auto it = std::find(conditions.begin(), conditions.end(), condition);
	if (it == conditions.end()) {
		return;
	}
```

### PR DESCRIPTION
**Pull request by Erza**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

A copy of the Condition object was added to the creature in `LuaScriptInterface::luaCreatureAddCondition`, therefore `Creature::removeCondition` could not remove the condition properly, as the Condition object that was constructed from Userdata did not match the one stored in the creature's condition list.

Also applied const correctness.

**Issues addressed:** closes #3544 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by MillhioreBT** [comment]
If you use logic, you will realize that this PR does not make any sense

This function has two behaviors:
* Remove by userdata: this gives us to understand that we need to pass the correct user data stored in the player conditions, if you pass a random or self-generated condition then it is very obvious that it will not remove anything since you random condition is not a player condition

* Remove by type: this is the behavior of a lifetime, you specify the search parameters, and if these parameters match any condition stored in the player then we obtain this condition and eliminate it

**¿How to use the function correctly with userdata?**
```lua
creature:removeCondition(creature:getCondition(...), ...)
```

*If you still insist, you can add an overload in lua and it looks much better, although counterintuitive and can lead people to think incorrectly, it is already out of basic logic.*

**Comment by Erza** [comment]
> If you use logic, you will realize that this PR does not make any sense
> 
> This function has two behaviors:
> 
> * Remove by userdata: this gives us to understand that we need to pass the correct user data stored in the player conditions, if you pass a random or self-generated condition then it is very obvious that it will not remove anything since you random condition is not a player condition
> * Remove by type: this is the behavior of a lifetime, you specify the search parameters, and if these parameters match any condition stored in the player then we obtain this condition and eliminate it
> 
> **¿How to use the function correctly with userdata?**
> 
> ```lua
> creature:removeCondition(creature:getCondition(...), ...)
> ```
> 
> _If you still insist, you can add an overload in lua and it looks much better, although counterintuitive and can lead people to think incorrectly, it is already out of basic logic._

Read https://github.com/otland/forgottenserver/issues/3544#issuecomment-894699556

**Comment by MillhioreBT** [comment]
> > If you use logic, you will realize that this PR does not make any sense
> > This function has two behaviors:
> > 
> > * Remove by userdata: this gives us to understand that we need to pass the correct user data stored in the player conditions, if you pass a random or self-generated condition then it is very obvious that it will not remove anything since you random condition is not a player condition
> > * Remove by type: this is the behavior of a lifetime, you specify the search parameters, and if these parameters match any condition stored in the player then we obtain this condition and eliminate it
> > 
> > **¿How to use the function correctly with userdata?**
> > ```lua
> > creature:removeCondition(creature:getCondition(...), ...)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _If you still insist, you can add an overload in lua and it looks much better, although counterintuitive and can lead people to think incorrectly, it is already out of basic logic._
> 
> Read [#3544 (comment)](https://github.com/otland/forgottenserver/issues/3544#issuecomment-894699556)

And I understand what you mean by using a condition and then extracting its properties and then finding the player's condition and so bla bla bla
I thought about this first than you, before this feature was added, but then I realized that it is just an additional complication
For example, what happens if we pass the correct user data? in this case we have to look for it again and it is like a pretty silly code

In case you are too lazy to write 20 more letters you can do a help function:
`data/lib/core/condition.lua`
```lua
function Condition:unpack()
	return self:getType(), self:getId(), self:getSubId()
end
```

`script.lua`
```lua
creature:removeCondition(condition:unpack())
```

**Review by DSpeichert — APPROVED** [review]
I'm not entirely against it, although we may be requiring in other places the Lua developer to also pass actual condition, not a replica. This behavior does not hurt though.

File: src/luascript.cpp [hunk 1]
```diff
@@ -7764,29 +7764,32 @@ int LuaScriptInterface::luaCreatureRemoveCondition(lua_State* L)
 {
 	// creature:removeCondition(conditionType[, conditionId = CONDITIONID_COMBAT[, subId = 0[, force = false]]])
 	// creature:removeCondition(condition[, force = false])
-	Creature* creature = getUserdata<Creature>(L, 1);
+	Creature* const creature = getUserdata<Creature>(L, 1);
```
Comment (ranisalt) [inline src/luascript.cpp:7767]: This is not necessary

Comment (ranisalt) [inline src/luascript.cpp:7767]: This is not necessary

**Comment by Codinablack** [comment]
All checks passing, all reviews passing. LGTM

PR is from 2021, its amazing its still able to be merged... Can we do so now?

**Review by MillhioreBT — APPROVED** [review]
