### PR TITLE
Fix #1436 - guild rank/level bug

### LINKED ISSUE #1436: Guild Rank bug when have more than 3 different ranks
I noticed that I have a bug on my guild rank, what happens:

If I have more than 1 guild rank (names) for the same level access, it will show on your player the first created rank, for instance:

ID ---- Guild ID ---------- RANK ---------- LEVEL
1 ----- 7 ------------------- 3 -------------- Owner
2 ----- 7 ------------------- 2 -------------- Sub-owner
3 ----- 7 ------------------- 1 -------------- Sorcerer rank
4 ----- 7 ------------------- 1 -------------- Paladin rank
5 ----- 7 ------------------- 1 -------------- Druid rank
6 ----- 7 ------------------- 1 -------------- Knight rank

What happens is that all players in ranks after "Sorcerer rank" will appear ingame as "Sorcerer Rank".
Someone have noticed it? There is any fix for that?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/23421493-guild-rank-bug-when-have-more-than-3-different-ranks?utm_campaign=plugin&utm_content=tracker%2F392151&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F392151&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ranisalt**
Currently, a guild is limited to only 3 ranks, one for leaders, one for vice-leaders and another for members. If you try to create more member levels, you end up with the description on look showing you the first rank created, not the actual one you are using (please see #1436 for further details).

This fixes the problem by the player holding its guild rank id instead of level. The only drawback is that the `Player:setGuildLevel` function is not reliable anymore, but it is rather useless when using an external guild management such as an AAC.

### CODE REVIEW

File: src/player.h [hunk 1]
```diff
@@ -237,11 +237,11 @@ class Player final : public Creature, public Cylinder
 			this->guild = guild;
 		}
 
-		uint8_t getGuildLevel() const {
-			return guildLevel;
+		GuildRank* getGuildRank() const {
+			return guild->getRankById(guildRank);
```
Comment (marksamman) [inline src/player.h]: Null pointer dereference if player has no guild.

File: src/luascript.cpp [hunk 2]
```diff
@@ -8098,7 +8098,7 @@ int LuaScriptInterface::luaPlayerSetGuildLevel(lua_State* L)
 	uint8_t level = getNumber<uint8_t>(L, 2);
 	Player* player = getUserdata<Player>(L, 1);
 	if (player) {
-		player->setGuildLevel(level);
+		player->setGuildRank(player->getGuild()->getRankByLevel(level));
```
Comment (marksamman) [inline src/luascript.cpp]: Null pointer dereference if player has no guild.

File: src/luascript.cpp [hunk 3]
```diff
@@ -8085,7 +8085,7 @@ int LuaScriptInterface::luaPlayerGetGuildLevel(lua_State* L)
 	// player:getGuildLevel()
 	Player* player = getUserdata<Player>(L, 1);
 	if (player) {
-		lua_pushnumber(L, player->getGuildLevel());
+		lua_pushnumber(L, player->getGuildRank()->level);
```
Comment (marksamman) [inline src/luascript.cpp]: Null pointer dereference if player has no guild.

**Comment by ranisalt** [comment]
Fixed null pointer dereferences

**Comment by marksamman** [comment]
Change guildRank in Player to a pointer to GuildRank.
Spell out GuildRank* instead of using auto.

File: src/luascript.cpp [hunk 4]
```diff
@@ -8097,8 +8097,8 @@ int LuaScriptInterface::luaPlayerSetGuildLevel(lua_State* L)
 	// player:setGuildLevel(level)
 	uint8_t level = getNumber<uint8_t>(L, 2);
 	Player* player = getUserdata<Player>(L, 1);
-	if (player) {
-		player->setGuildLevel(level);
+	if (player && player->getGuild()) {
+		player->setGuildRank(player->getGuild()->getRankByLevel(level));
```
Comment (marksamman) [inline src/luascript.cpp]: You should push false to Lua if getRankByLevel returns null, and not set the guild rank in that case. It could cause a null pointer dereference in Player.getGuildLevel() if the player is in a guild but the rank is null.

File: src/iologindata.cpp [hunk 5]
```diff
@@ -389,12 +389,7 @@ bool IOLoginData::loadPlayer(Player* player, DBResult_ptr result)
 
 		if (guild) {
 			player->guild = guild;
-			GuildRank* rank = guild->getRankById(playerRankId);
-			if (rank) {
-				player->guildLevel = rank->level;
-			} else {
-				player->guildLevel = 1;
-			}
+			player->guildRank = guild->getRankById(playerRankId);
```
Comment (marksamman) [inline src/iologindata.cpp]: guildRank can be null if the rank id of this player was inserted to the database after the first time someone in the guild logged in. The rank should be added to the guild if it does not currently exist.

**Comment by marksamman** [comment]
Please rebase off master and also update Player::setGuild()

**Comment by ranisalt** [comment]
I think it's ok now. I'm not sure if I should check on `setGuildRank` if the rank exists in the player's guild or just let it be.

File: src/luascript.cpp [hunk 6]
```diff
@@ -8090,11 +8090,15 @@ int LuaScriptInterface::luaPlayerSetGuildLevel(lua_State* L)
...
-		lua_pushnil(L);
+		if (const Guild* guild = player->getGuild()) {
+			if (const GuildRank* rank = guild->getRankByLevel(level)) {
+				player->setGuildRank(rank);
+				pushBoolean(L, true);
+				return 1;
+			}
+		}
 	}
+	pushBoolean(L, false);
```
Comment (marksamman) [inline src/luascript.cpp]: Please invert the if-statements to avoid deep indentation, and this should push nil if player is null.

File: src/iologindata.cpp [hunk 7]
```diff
@@ -389,13 +389,20 @@ bool IOLoginData::loadPlayer(Player* player, DBResult_ptr result)
...
+			const GuildRank* rank = guild->getRankById(playerRankId);
+			if (!rank) {
+				query.str(std::string());
+				query << "SELECT `id`, `name`, `level` FROM `guild_ranks` WHERE `id` = " << playerRankId;
+
+				if ((result = db->storeQuery(query.str()))) {
+					guild->addRank(result->getNumber<uint32_t>("id"), result->getString("name"), result->getNumber<uint16_t>("level"));
+				}
+
+				rank = guild->getRankById(playerRankId);
```
Comment (marksamman) [inline src/iologindata.cpp]: This can be null if the row is deleted from the database between the time of selecting players rank id and querying rank information. In that case, the player should be loaded without a guild (guild as nullptr, no guild nick, no guild war list).

**Comment by brunominervino** [comment]
@ranisalt, this changes are working 100%?

**Comment by ranisalt** [comment]
@brunominervino yes, it works

**Comment by brunominervino** [comment]
@ranisalt thank you so much, I will test in my project.

File: src/luascript.cpp (hunk 6 above)
Comment (ranisalt) [inline src/luascript.cpp]: Fixed, I guess. Now pushes nil if either player is null or player guild is null, and pushes false if there's no rank available.

**Comment by ranisalt** [comment]
Rebased and fixed.

**Comment by marksamman** [comment]
Thanks!
