### PR TITLE
Handle exception when map file does not exist

### LINKED ISSUE #3254: Server closes on non-existing map name
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Change default mapName in config.lua to something that doesn't exist

### Expected behaviour
Console should give at least some info what have gone wrong. For example: couldn't find map file.

### Actual behaviour
The server closes unexpectedly without giving any info. Screenshot included:
image

### PR DESCRIPTION
**Pull request by nekiro**
Fix #3254

### CODE REVIEW

File: src/iomap.cpp [hunk 1]
```diff
@@ -69,85 +69,90 @@ Tile* IOMap::createTile(Item*& ground, Item* item, uint16_t x, uint16_t y, uint8
 bool IOMap::loadMap(Map* map, const std::string& fileName)
 {
 	int64_t start = OTSYS_TIME();
-	OTB::Loader loader{fileName, OTB::Identifier{{'O', 'T', 'B', 'M'}}};
-	auto& root = loader.parseTree();
+	try {
```
Comment (djarek) [inline src/iomap.cpp:72]: I don't like the scope of this `try` block, it catches a lot more errors than it should, e.g. if something throws during tile parsing, we may end up in an inconsistent state.

Comment (nekiro) [reply src/iomap.cpp:72]: Well I wanted to catch only the constructor, but I couldn't because of the variable being enclosed in try catch block, thus rest of the code wont proceed. I could probably use pointer for this though.

Comment (djarek) [reply src/iomap.cpp:72]: Hmm, this is actually a tough one, because parsing props may still cause us to end up in a partially-loaded state. I usually prefer to make such operations "transactional" (either succeeds completely or has no effect), but I guess it's way out of scope of this PR. 

I think it's sufficient to just change the type you accept in `catch` to `catch (const InvalidOTBFormat& err)`

Comment (nekiro) [reply src/iomap.cpp:72]: Honestly gonna sound like a noob here, but I tried but couldn't make it to work. No matter what I did it wouldn't find the custom exception type. I included fileloader.h on the top and still wasn't able to find it somehow...

Comment (djarek) [reply src/iomap.cpp:72]: `const OTB::LoadError&` should work just fine.

**Review by djarek — APPROVED** [review]
LGTM
