### PR TITLE
Fix: Price of NPC's items

### LINKED ISSUE #4292: Price of incorrect items
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Open any buy and sell NPC and add a list of products if there are not enough some values will be incorrect.

### Expected behaviour 
Show the correct values.

### Actual behaviour 
Sem título

### PR DESCRIPTION
**Pull request by omarcopires**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed 
Fixes the window for buying and selling items on NPC's.

Credits: @Zbizu

**Issues addressed:** 
Closes #4292

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

File: src/enums.h [hunk 1]
```diff
@@ -560,12 +560,12 @@ struct ShopInfo
 {
 	uint16_t itemId = 0;
 	int32_t subType = 1;
-	int64_t buyPrice = 0;
-	int64_t sellPrice = 0;
+	uint32_t buyPrice = 0;
+	uint32_t sellPrice = 0;
```
Comment (DSpeichert) [inline src/enums.h:564]: Why not uint64_t? Didn't the client start accepting larger numbers recently?

Comment (omarcopires) [reply src/enums.h:564]: Values currently allowed in version 13.x do not exceed the uint32_t limits.

**Review by EPuncker — APPROVED** [review]

File: data/npc/lib/npcsystem/modules.lua [hunk 2]
```diff
@@ -960,7 +960,7 @@ if not Modules then
 			return false
 		end
 
-		if shopItem.buy == -1 then
+		if shopItem.buy == 0 then
```
Comment (Kamenuvol) [inline data/npc/lib/npcsystem/modules.lua:963]: I think it should be a valid value to buy/sell for free. To not me buyable/sellable the value in Lua table should be nil.

Comment (EPuncker) [reply data/npc/lib/npcsystem/modules.lua:963]: I don't think the client can handle that (haven't tested), since cip sell items for 1 gp at testserver assistant and not 0 (for free)
