### PR TITLE
RevScriptSys Monster enhanced attack conditions

### LINKED ISSUE #3485: Revscriptsys Monster
Well, I don't know if this is supposed to happen, but, when I try to register a monster using revscript and register a scripted spell such as sudden death rune, rage of the skies, energy strike, it doesn't work: it causes no damage.

### Steps to reproduce
1. Register a monster using revscriptsys
2. Set up the monster to use a scripted spell (sudden death rune or rage of the skies, for example)
3. Wait until the monster cast it, you'll notice that it'll cause 0 damage

### Expected behaviour
Cause the damage registered as minDamage and maxDamage

### Actual behaviour
The monster is causing 0 damage

### Environment
Windows 10

### PR DESCRIPTION
**Pull request by soul4soul**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
**Issues addressed:** 

- Fix #3485 
- Refactor parsing revscriptsys monster attack and defense to use a common helper function
- Allow conditions to be used with all predefine creature abilities. Conditions can be used with "melee", "combat", "speed", "condition", "outfit", "invisible", "*field", etc.. Conditions won't work with named spells such as "energy strike".

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

I verified conditions worked using these attack types. 
```
monster.attacks = {
	{name = "melee", attack = 10, skill = 100, condition = { type = CONDITION_FIRE, minDamage = 50, maxDamage = 200, duration = 5000, interval = 1000}},
        {name = "condition", chance = 1000, range = 1, condition = { type = CONDITION_ENERGY, minDamage = 10, maxDamage = 20, duration = 5000, interval = 1000}},
        {name = "combat", type = COMBAT_LIFEDRAIN, chance = 100, interval = 2*1000, minDamage = 0, maxDamage = -10, target = true, range = 7, condition = { type = CONDITION_CURSED, minDamage = 10, maxDamage = 20, duration = 5000, interval = 1000}},
        {name = "speed", chance = 100, interval = 2000, speed = -500, target = true, range = 7, condition = { type = CONDITION_DROWN, minDamage = 20, maxDamage = 20, duration = 5000, interval = 1000}},
        {name = "firefield", chance = 100, interval = 2000, target = true, range = 7, condition = { type = CONDITION_FREEZING, minDamage = 20, maxDamage = 50, duration = 5000, interval = 1000}}
}
```

### CODE REVIEW

File: data/scripts/lib/register_monster_type.lua [hunk 1]
```diff
@@ -394,120 +277,119 @@ registerMonsterType.defenses = function(mtype, mask)
...
-					end
-					if defense.direction then
-						spell:setNeedDirection(defense.direction)
+				local spell = AbilityTableToSpell(defense)
+				mtype:addDefense(spell)
+			end
+		end
+	end
+end
+function AbilityTableToSpell(ability)
```
Comment (EPuncker) [inline data/scripts/lib/register_monster_type.lua:286]: shouldn't this be added a few lines above before it is used?

Comment (MillhioreBT) [reply data/scripts/lib/register_monster_type.lua:286]: The libraries are loaded first, so there is no problem with the order of declaration, however it does not seem intuitive and it makes more sense to have it declared before it is used.

Comment (soul4soul) [reply data/scripts/lib/register_monster_type.lua:262]: Didn't even think about it I'm so use to languages which don't care. Moved the function above the usage.

File: data/scripts/lib/register_monster_type.lua [hunk 2]
```diff
@@ -259,127 +259,120 @@ registerMonsterType.immunities = function(mtype, mask)
...
+			if ability.name == "drunk" then
+				spell:setConditionType(CONDITION_DRUNK)
+				if ability.drunkenness then
+					spell:setConditionDrunkenness(ability.drunkenness)
 				end
 			end
+		end
+		if ability.condition then
+			if ability.condition.type then
+				print(ability.condition.type)
```
Comment (MillhioreBT) [inline data/scripts/lib/register_monster_type.lua:335]: and this?

**Review by MillhioreBT — CHANGES_REQUESTED** [review]

File: data/scripts/lib/register_monster_type.lua (hunk 2 above)
Comment (MillhioreBT) [reply data/scripts/lib/register_monster_type.lua:335]: and why not make the `AbilityTableToSpell` function local? from what I see, it will only be used in this file

**Review by EPuncker — APPROVED** [review]

**Review by EPuncker — APPROVED** [review]
