### PR TITLE
Fix #2074 double door listing on houses

### LINKED ISSUE #2074: Multiple database entries for the same house door list
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Own a guild hall
2. Add a player to a door list with aleta grav
3. Save the server

### Expected behaviour
A single entry in the `house_lists` table should be used to store that door name list.

### Actual behaviour
Multiple entries with the same content are stored

Imgur

### PR DESCRIPTION
**Pull request by ranisalt**
Changing from list to set seems to fix as the same door is no longer double inserted. Also it reduces complexity of searching for a door to logarithmic.

Fixes #2074.

### CODE REVIEW

File: src/house.h [hunk 1]
```diff
@@ -234,7 +235,7 @@ class House
 		Container transfer_container{ITEM_LOCKER1};
 
 		HouseTileList houseTiles;
-		std::list<Door*> doorList;
+		std::set<Door*> doorSet;
```
Comment (djarek) [inline src/house.h]: std::unordered_set?

Comment (ranisalt) [inline src/house.h]: I'm not sure the overhead is worth it. Most houses don't even have internal doors, and guild halls generally between 4 and 8 AFAIK.

**Comment by ranisalt** [comment]
Thanks!  🤣
