### PR TITLE
fix #2843

### LINKED ISSUE #2843: Loot from monsters does not check if string is correct
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Ex in #2842, TFS does not check (/ report an error) when the item does not exist

### Expected behaviour

Throw an error that the item does not exist

### Actual behaviour

Nothing

### Environment

Does not matter AFAIK

### PR DESCRIPTION
**Pull request by EvilHero90**
Added to config.lua
- forceMonsterTypesOnLoad (default = true)

People can decide on their own if they want to load all MonsterTypes immediatly on server startup or not.
This adresses the issue in #2843

### CODE REVIEW

**Comment by Znote** [comment]
Does this also work together with #2798 to grab all registered xml monster types (even ones that arent used)?

**Comment by EvilHero90** [comment]
Yes, Game.getMonsterTypes() will return in this case all monsters, from monsters.xml

**Comment by nekiro** [comment]
Imo it should be false by default not true, why would we want to load all monster types into memory? If they arent used

**Comment by EvilHero90** [comment]
It should be load as default in debug mode, so it shows errors immediatly as @WibbenZ already said in #2843 
I can add a console debug print, so people are aware it's enabled, so they can turn it off themselves.

**Comment by EvilHero90** [comment]
Implemented revscriptsys checks for loot
tfs5

File: src/luascript.cpp [hunk 1]
```diff
@@ -13111,13 +13111,28 @@ int LuaScriptInterface::luaLootSetId(lua_State* L)
...
+
+			uint32_t id = ids.first->second;
+
+			if (std::next(ids.first) != ids.second) {
+				std::cout << "[Warning - Loot:setId] Non-unique loot item \"" << name << "\". " << std::endl;
+				pushBoolean(L, false);
+				return 1;
+			}
+
+			loot->lootBlock.id = id;
```
Comment (WibbenZ) [inline src/luascript.cpp]: loot->lootBlock.id = ids.first->second
I don't see a reason to create the variable since you don't use it anywhere else

File: data/scripts/lib/register_monster_type.lua [hunk 2]
```diff
@@ -159,9 +159,12 @@ registerMonsterType.events = function(mtype, mask)
 end
 registerMonsterType.loot = function(mtype, mask)
 	if type(mask.loot) == "table" then
+		local lootError = false
 		for _, loot in pairs(mask.loot) do
 			local parent = Loot()
-			parent:setId(loot.id)
+			if not parent:setId(loot.id) then
+				lootError = true
```
Comment (WibbenZ) [inline data/scripts/lib/register_monster_type.lua]: Would be a good ide to print out the id / name + you can remove the lootError code and just print here insted
Same for line 187

Comment (EvilHero90) [reply data/scripts/lib/register_monster_type.lua]: The error handling print is done in the c++ function, so we can differentiate the error.
If I moved the print inside here it would result in double the prints for actually no reason, it doesn't need to remind me after every line that this monster has an error, I'd rather have a summary of errors and at the end it shows which monster it is.

File: src/luascript.cpp (hunk 1 above)
Comment (EvilHero90) [reply src/luascript.cpp]: removed it
