### PR TITLE
Fix #3951 Bank NPC transfer errors

### LINKED ISSUE #3951: Error in script bank.lua
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. hi, to NPC banker.
2. transfer
3. name that does not exist

### Expected behaviour
reply that the player does not exist

### Actual behaviour
image

### Reproduction environment
https://github.com/otland/forgottenserver/blob/master/data/npc/scripts/bank.lua

### PR DESCRIPTION
**Pull request by Znote**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Resolves 2 errors in bank NPC when trying to transfer money to another player.
- If you specified a word instead of a number, NPC would throw a console error. Now it will repeat the question and ask specifically for a number.
- If you specified a player name that didnt exist, NPC would throw a console error. Now it will inform user that it failed to find anyone with that name, and that he should make sure the name is correct. 

**Issues addressed:** 
#3951

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

File: data/npc/scripts/bank.lua [hunk 1]
```diff
@@ -233,6 +233,12 @@ local function creatureSayCallback(cid, type, msg)
 			end
 		end
 	elseif npcHandler.topic[cid] == topicList.TRANSFER_PLAYER_GOLD then
+		local currencyValue = tonumber(msg)
```
Comment (dbjorkholm) [inline data/npc/scripts/bank.lua:236]: Better off making sure `getMoneyCount` returns a numeric value that is acceptable rather than adding checks like this (which may be required in other places as well).

File: data/npc/scripts/bank.lua [hunk 2]
```diff
@@ -248,6 +254,11 @@ local function creatureSayCallback(cid, type, msg)
 		end
 	elseif npcHandler.topic[cid] == topicList.TRANSFER_PLAYER_WHO then
 		transfer[cid] = getPlayerDatabaseInfo(msg)
+		if not transfer[cid] then
```
Comment (dbjorkholm) [inline data/npc/scripts/bank.lua:257]: You may want to add this if-statement to L210 as well as removing the redundant `if transfer[cid] then` in both places.

File: data/npc/scripts/bank.lua (hunk 1 above)
Comment (luanluciano93) [reply data/npc/scripts/bank.lua:236]: In https://github.com/otland/forgottenserver/blob/4929928966abdfbdb786d5ed297034785d08edf8/data/npc/scripts/bank.lua#L141 change ` if isValidMoney(count[cid]) then` to `if count[cid] ~= -1 then` ?

Comment (luanluciano93) [reply data/npc/scripts/bank.lua:236]: `				-- Immediate topicList.TRANSFER_PLAYER_GOLD simulation
				count[cid] = getMoneyCount(parts[2])
				if count[cid] ~= -1 then
					if player:getBankBalance() < count[cid] then
						npcHandler:say("There is not enough gold in your account.", cid)
						npcHandler.topic[cid] = topicList.NONE
						return true
					end
					npcHandler:say("Who would you like transfer " .. count[cid] .. " gold to?", cid)
					npcHandler.topic[cid] = topicList.TRANSFER_PLAYER_WHO
				else
					npcHandler:say("There is not enough gold in your account.", cid)
					npcHandler.topic[cid] = topicList.NONE
				end`

**Comment by luanluciano93** [comment]
Can check that way Znote? https://pastebin.com/raw/zKNLKi7z

**Comment by Znote** [comment]
I'm sure there is lots of refactoring and improvements to be made to NPC scripts and the associated lib functions, but this PR specifically is made to resolve 2 errors currently present within the bank NPC. 

But feel free to push commits to the [bankfix](https://github.com/Znote/forgottenserver/tree/bankfix) branch on [Znote/forgottenserver](https://github.com/Znote/forgottenserver) for improvements and further fixes. 

@luanluciano93 
> Can check that way @Znote? https://pastebin.com/raw/zKNLKi7z

That code does not resolve the first error specified in my changes proposed list. 
And why are you using pastebin in the land of git? 😄

**Review by DSpeichert — APPROVED** [review]
