### PR TITLE
Kick players while they are attacking or attacked by monsters (when afk)

### LINKED ISSUE #2871: kickIdlePlayerAfterMinutes - It's not working TFS 1.3
Hi,
when I attack any monster and stay without move more that 15minut my character should be kicked but it is not. The same is with exit. When I attack monster and exit game character will stay and stay.
I don't have na logout zones etc.

### PR DESCRIPTION
**Pull request by nekiro**
Fix #2871

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -3182,7 +3184,7 @@ void Player::doAttacking(uint32_t)
 
 		SchedulerTask* task = createSchedulerTask(std::max<uint32_t>(SCHEDULER_MINTICKS, delay), std::bind(&Game::checkCreatureAttack, &g_game, getID()));
 		if (!classicSpeed) {
-			setNextActionTask(task);
+			setNextActionTask(task, false);
 		} else {
 			g_scheduler.addEvent(task);
```
Comment (slavidodo) [inline src/player.cpp:3189]: does this introduces any inconsistency?

Comment (nekiro) [reply src/player.cpp:3189]: Not sure what you mean by that, I added optional parameter to this method, which by default is previous behaviour
